### ISSUE TITLE
I got error when using 'instantly help'

### ISSUE THREAD

**Issue by yinghunshen** [timothycrosley/instantly#1]
Hi, 

After I installed instantly, I got error when using 'instantly help'. The followings are the error prompt:

Traceback (most recent call last):
  File "/usr/local/python273/bin/instantly", line 106, in <module>
    copy_tree(InstantlyFiles.**path**[0] + "/instant_templates/", TEMPLATE_PATH)
  File "/usr/local/python273/lib/python2.7/distutils/dir_util.py", line 128, in copy_tree
    "cannot copy tree '%s': not a directory" % src
distutils.errors.DistutilsFileError: cannot copy tree '/usr/local/python273/lib/python2.7/site-packages/Instantly-0.8.0-py2.7.egg/InstantlyFiles/instant_templates/': not a directory

can you help me?

thanks,

Sam

**Comment by timothycrosley** [comment]
Hi Sam,

Sorry for the delay, this should be fixed with the latest version of instantly

Thanks!

~Tim
