### ISSUE TITLE
'pip install instantly' blows up if you haven't already installed pies

### ISSUE THREAD

**Issue by madirey** [timothycrosley/instantly#2]
Because of this line:

   from pies.overrides import *

Any way to fix this?  Didn't see it addressed in the documentation.

**Comment by timothycrosley** [comment]
Thanks for reporting!

Really there's no reason for pies to be included in setup.py, but just made it's way there by my overly lazy usage of "isort -a 'from pies import _' -a ' from **future** import absolute_import, division, print_function, unicode_literals' *_/*.py"

Fixed in version 0.8.5

**Comment by madirey** [comment]
sweetness!
